### ISSUE TITLE
How do we style the children differently?

### ISSUE THREAD

**Issue by bharathitman** [ethanhann/eeh-navigation#46]
The way it works currently is both the parent and the active child get  highlighted in the same color / style. In certain color schemes, the whole thing looks gaudy.

![image](https://cloud.githubusercontent.com/assets/994536/13157726/8a446f86-d6af-11e5-8242-7fb5b92bf3ff.png)

Is their any way where in I can style the active child differently so as to clearly differentiate between parent and child (other than the indentation).

P.S : I went through a bit of source code, seems like both the parent and repeating children get the class 'active'.

**Comment by ethanhann** [comment]
Child items have the "leaf" class. You could use that class to do some theming.

For active child menu items:

``` css
.eeh-navigation-sidebar li.leaf.active {
    background-color: #FFF;
    color: #000;
}
```

For active parent menu items:

``` css
.eeh-navigation-sidebar li:not(.leaf).active {
    background-color: #FFF;
    color: #000;
}
```
